services:
  - type: web
    name: memedici-backend
    env: python
    plan: starter
    rootDir: ./backend
    buildCommand: |
      # Install Node.js and npm
      curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      sudo apt-get install -y nodejs
      # Install Python dependencies
      pip install poetry && poetry config virtualenvs.create false && poetry install --only=main
      # Install Lighthouse CLI
      npm install -g @lighthouse-web3/sdk
      # Make the setup script executable and run it
      chmod +x ./utils/setup_lighthouse_cli.sh
      ./utils/setup_lighthouse_cli.sh
    startCommand: poetry run uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: NOVITA_API_KEY
        sync: false
      - key: LIGHTHOUSE_API_KEY
        sync: false
      - key: LIGHTHOUSE_CLI_PWD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: memedici-db
          property: connectionString
    healthCheckPath: /health
    
databases:
  - name: memedici-db
    databaseName: memedici
    user: memedici_user 